In [2]:
import numpy as np

In [30]:
arr1=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
arr1.reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [31]:
arr1[arr1%2==1]=-1
arr1

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8])

In [21]:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89]) 
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])
print(np.where(x>y))
print(np.where(x==y))

(array([1, 2, 4, 5, 6, 7, 8, 9]),)
(array([0]),)


In [25]:
np.arange(100).reshape(5,-1)[:,:4]

array([[ 0,  1,  2,  3],
       [20, 21, 22, 23],
       [40, 41, 42, 43],
       [60, 61, 62, 63],
       [80, 81, 82, 83]])

In [13]:
np.random.randint(30,41,10)

array([40, 38, 36, 34, 37, 31, 33, 34, 40, 31])

In [19]:
A=np.array([(1,2,3),(4,5,6),(7,8,10)])
B=np.array([(7,8,10),(4,5,6),(1,2,3)])
C=np.add(A,B)
E=np.subtract(A,B)
print(C)
print(E)
print(np.sum(A))
print(np.sum(B,axis=0))
print(np.sum(B,axis=1))
D=A*B
print(D)
E=np.sort(C,axis=None).reshape((3,3))
print(E)
print(np.transpose(E))

[[ 8 10 13]
 [ 8 10 12]
 [ 8 10 13]]
[[-6 -6 -7]
 [ 0  0  0]
 [ 6  6  7]]
46
[12 15 19]
[25 15  6]
[[ 7 16 30]
 [16 25 36]
 [ 7 16 30]]
[[ 8  8  8]
 [10 10 10]
 [12 13 13]]
[[ 8 10 12]
 [ 8 10 13]
 [ 8 10 13]]
