In [1]:
import torch
import numpy as np

In [14]:
# 1. Illustrate the functions for Reshaping, viewing, stacking, squeezing and unsqueezing of tensors
x = torch.tensor([1,2,3,4,5,6,7,8])
print("x:",x)
y = torch.reshape(x, (2, 4))
print("After Reshaping:\n",y)

y = x.view(4,2)
print("After viewing:\n",y)

y = torch.stack([x, x], dim=0)
print("After stacking:\n",y)  

y = x.unsqueeze(0)
print("After unsqueeze:\n",y)

y = y.squeeze(0)
print("After squeeze:\n",y)

x: tensor([1, 2, 3, 4, 5, 6, 7, 8])
After Reshaping:
 tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
After viewing:
 tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
After stacking:
 tensor([[1, 2, 3, 4, 5, 6, 7, 8],
        [1, 2, 3, 4, 5, 6, 7, 8]])
After unsqueeze:
 tensor([[1, 2, 3, 4, 5, 6, 7, 8]])
After squeeze:
 tensor([1, 2, 3, 4, 5, 6, 7, 8])


In [18]:
# 2. Illustrate the use of torch.permute().
y = torch.rand(1,2)
print("Initial Tensor:\n",y,"\nwith size:",y.shape)
perm = torch.permute(y,(1, 0))
print("New tensor\n", perm,"\nwith size:",perm.shape)

Initial Tensor:
 tensor([[0.7204, 0.0731]]) 
with size: torch.Size([1, 2])
New tensor
 tensor([[0.7204],
        [0.0731]]) 
with size: torch.Size([2, 1])


In [4]:
#3. Illustrate indexing in tensors
print(x[0:2])

tensor([1, 2])


In [5]:
#4. Show how numpy arrays are converted to tensors and back again to numpy arrays
x=np.arange(7)
print(x)
y=torch.tensor(x)
print(y)

[0 1 2 3 4 5 6]
tensor([0, 1, 2, 3, 4, 5, 6])


In [6]:
# 5.Create a random tensor with shape (7, 7).
x = torch.rand(7,7)
x

tensor([[0.9070, 0.0695, 0.3877, 0.4942, 0.0465, 0.9684, 0.2225],
        [0.7860, 0.7744, 0.4969, 0.6347, 0.8878, 0.3036, 0.9189],
        [0.8416, 0.3911, 0.1783, 0.2463, 0.8715, 0.9748, 0.0254],
        [0.7444, 0.5154, 0.7098, 0.0557, 0.8983, 0.8995, 0.8743],
        [0.5543, 0.8133, 0.8391, 0.0928, 0.4552, 0.1626, 0.2433],
        [0.7162, 0.4683, 0.5887, 0.1860, 0.0855, 0.5133, 0.0457],
        [0.8672, 0.0789, 0.3647, 0.7031, 0.5716, 0.2278, 0.6455]])

In [7]:
# 6. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).
x=torch.randn(1,7)
mul=perm@x
print(mul)

tensor([[-0.1153,  2.3253, -0.0745, -0.5434, -0.4562,  0.2624, -0.4672],
        [-0.0643,  1.2972, -0.0416, -0.3031, -0.2545,  0.1464, -0.2606]])


In [8]:
# 7. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this).

a = torch.randn(2, 3).to("cuda")
b = torch.randn(2, 3).to("cuda")
print("Tensor 1 on GPU:", a)
print("Tensor 2 on GPU:", b)

Tensor 1 on GPU: tensor([[ 0.6015,  0.0174, -0.4183],
        [-0.0160, -0.3691,  1.0434]], device='cuda:0')
Tensor 2 on GPU: tensor([[-0.8957,  0.2164,  0.6484],
        [-0.4722, -0.2446, -0.8843]], device='cuda:0')


In [9]:
# 8. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
print(mul@mul.T)

tensor([[6.2167, 3.4680],
        [3.4680, 1.9347]])


In [10]:
# 9. Find the maximum and minimum values of the output of 7.
maxa=torch.max(a)
mini=torch.min(a)
print(f"Max value:{maxa}, Min value:{mini} in {a}")

Max value:1.0434134006500244, Min value:-0.4182544946670532 in tensor([[ 0.6015,  0.0174, -0.4183],
        [-0.0160, -0.3691,  1.0434]], device='cuda:0')


In [11]:
# 10. Find the maximum and minimum index values of the output of 7.
maxa=torch.argmax(a)
mini=torch.argmin(a)
print(f"Max Index value:{maxa}, Min Index value:{mini}")

Max Index value:5, Min Index value:2


In [12]:
# 11. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.
torch.manual_seed(7)
x = torch.rand((1,1,1,10))
print(f"Initial Tensor:{x} \n with shape: {x.shape}")
y=x.squeeze()
print(f"\nFinal Tensor:{y} \n with shape: {y.shape}")



Initial Tensor:tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) 
 with shape: torch.Size([1, 1, 1, 10])

Final Tensor:tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) 
 with shape: torch.Size([10])
